spring:
  application:
    name: db-server

server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'